from pinscrape import Pinterest
import json
import os
import random

keyword = "memesbr filosofia"
output_file = "Frontend/js/data/pinterest_data.js"
proxies = {}
number_of_workers = 10
images_to_download = 250  # Adjusted for testing, user can increase

# Mock data for generation
CAPTIONS = [
    "Filosofia moderna em uma imagem. #filosofia #humor",
    "Quando a crise existencial bate. #crise #existencialismo",
    "Só sei que nada sei. #socrates",
    "O mito da caverna versão 2024. #platao",
    "Penso, logo posto. #descartes",
    "Rindo para não chorar com o absurdo da vida. #camus",
    "A angústia é a vertigem da liberdade. #kierkegaard",
    "O inferno são os outros (nos comentários). #sartre",
    "Vontade de potência (de rir). #nietzsche",
    "A vida sem música (e memes) seria um erro. #nietzsche"
]

def generate_js_file(image_urls):
    print(f"Generating {output_file} with {len(image_urls)} images...")
    
    js_content = """/**
 * pinterest_data.js
 * 
 * Auto-generated by scrape_pinterest.py
 * Contains scraped images from Pinterest for "memesbr filosofia".
 */

export const PINTEREST_MEDIA = [
"""
    
    start_id = 3000
    
    for i, url in enumerate(image_urls):
        entry_id = start_id + i
        philosopher_id = random.randint(1, 15) # Assuming 15 philosophers
        likes = random.randint(50, 5000)
        caption = random.choice(CAPTIONS)
        
        entry = f"""    {{
        id: {entry_id},
        philosopherId: {philosopher_id},
        mediaUrl: '{url}',
        type: 'image',
        caption: '{caption}',
        likes: {likes},
        comments: []
    }},
"""
        js_content += entry

    js_content += "];\n"
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Successfully wrote to {output_file}")

def scrape_data():
    print(f"Scraping data for keyword: {keyword} using Pinterest class")
    
    try:
        p = Pinterest(proxies=proxies, sleep_time=2)
        # search returns a list of URLs
        images_url = p.search(keyword, images_to_download)
        
        print(f"\nFound {len(images_url)} URLs")
        
        if images_url:
            generate_js_file(images_url)
        else:
            print("No URLs found.")
            
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    scrape_data()
